### ISSUE TITLE
BarChart labels are in reverse order when using Firefox and ChartArea type is "ordinal"

### ISSUE THREAD

**Issue by SamKas** [jamestthompson3/viiksetjs#9]
BarChart labels are in reverse order when using Firefox and ChartArea type is "ordinal". Labels are in correct order when using Google Chrome or Microsoft Edge.

## Expected Behavior

Expected labels to match with respective values. "First" should have value of 1, "second" should have value of 2 and so on.

## Actual Behavior

Labels are displayed in reverse order. "Fifth" has value of 1, "fourth" has value of 2 and so on.

![issue](https://user-images.githubusercontent.com/13502437/50705841-c175af00-1064-11e9-8945-22021882d46a.png)

## Steps to Reproduce the Problem

1. Create app using "npx create-react-app my-app"
2. Navigate to app folder and install viiksetjs using "yarn add viiksetjs"
3. Give root component some size so chart is visible eg.
```
#root {
  width: 700px;
  height: 300px;
}
```

4. Paste following minimal example to App.js

```
import React, { Component } from 'react';
import { ChartArea, BarChart } from 'viiksetjs';

class App extends Component {
  render() {
    const data = [
      {xKey: 'first', dataKey: 1},
      {xKey: 'second', dataKey: 2},
      {xKey: 'third', dataKey: 3},
      {xKey: 'fourth', dataKey: 4},
      {xKey: 'fifth', dataKey: 5}
    ];
    return (
      <ChartArea
        data={data}
        xKey="xKey"
        type="ordinal"
      >
        <BarChart dataKey="dataKey" />
      </ChartArea>
    );
  }
}

export default App;
```

5. Run app using "yarn run start"
6. Open app in Firefox

## Specifications

Version: 0.0.29
Browser: Firefox Quantum 64.0 (64-bit)

**Comment by jamestthompson3** [comment]
Thanks for creating an issue! I'm currently rewriting the `ChartArea` API which will make things a bit simpler and will address this in the rewrite. Feel free to follow along [here](https://github.com/jamestthompson3/viiksetjs/tree/change-chartarea-api) or contribute!
